var uiModels = uiModels || {};
uiModels.comics_data = [{
  "title": "Do Androids Dream Of Electric Sheep?",
  "genre": 11,
  "authors": "Philip K Dick, Tony Parker",
  "complete": true,
  "finished": true,
  "have": "1-6",
  "have_nb": 6,
  "serie_nb": 6,
  "language": 1,
  "pix": "comics/androitsheep1.jpeg"
},
{
  "title": "Saga",
  "genre": 11,
  "authors": "Brian K. Vaughan and Fiona Staples",
  "complete": false,
  "finished": false,
  "have": "1-3",
  "have_nb": 3,
  "serie_nb": 4,
  "language": 1,
  "pix": "comics/saga1.jpeg"
},
{
  "title": "Alim le Tanneur",
  "genre": 5,
  "authors": "Wilfrid Lupano, Virginie Augustin",
  "complete": true,
  "finished": true,
  "have": "1-4",
  "have_nb": 4,
  "serie_nb": 4,
  "language": 2,
  "pix": "comics/alim1.jpg"
},
{
  "title": "La Caste des Meta-Barons",
  "genre": 11,
  "authors": "Alexandro Jodorowsky et Juan Gimenez",
  "complete": false,
  "finished": true,
  "have": "1-5",
  "have_nb": 5,
  "serie_nb": 8,
  "language": 2,
  "pix": "comics/metabaron1.jpeg"
},
{
  "title": "Garulfo",
  "genre": 7,
  "have": "1-6",
  "have_nb": 6,
  "serie_nb": 6,
  "language": 2,
  "authors": "Alain Ayroles et Bruno Maïorana",
  "complete": true,
  "finished": true,
  "pix": "comics/garulfo1.jpeg"
},
{
  "title": "Lanfeust de Troy",
  "genre": 5,
  "authors": "Didier Tarquin, Christophe Arleston",
  "complete": true,
  "finished": true,
  "have": "1-8",
  "have_nb": 8,
  "serie_nb": 8,
  "language": 2,
  "pix": "comics/lanfeust1.jpeg"
},
{
  "title": "Salammbo",
  "genre": 4,
  "authors": "Philippe Druillet et Gustave Flaubert",
  "complete": true,
  "finished": true,
  "have": "1-3",
  "have_nb": 3,
  "serie_nb": 3,
  "language": 2,
  "pix": "comics/salammbo1.jpeg"
},
{
  "title": "Blacksad",
  "genre": 10,
  "authors": "Juan Díaz Canales et Juanjo Guarnido",
  "complete": true,
  "finished": false,
  "have": "1-4",
  "have_nb": 4,
  "serie_nb": 4,
  "language": 2,
  "pix": "comics/blacksad1.jpeg"
},
{
  "title": "Carmen McCallum",
  "genre": 11,
  "authors": "Fred Duval et Gess",
  "complete": false,
  "finished": false,
  "have": "1-5",
  "have_nb": 5,
  "serie_nb": 12,
  "language": 2,
  "pix": "comics/carmenmc1.jpeg"
},
{
  "title": "Code McCallum",
  "genre": 11,
  "authors": "Fred Duval et Didier Cassegrain",
  "complete": true,
  "finished": true,
  "have": "5",
  "have_nb": 5,
  "serie_nb": 5,
  "language": 2,
  "pix": "comics/codemc1.jpeg"
},
{
  "title": "La Nef des Fous",
  "genre": 7,
  "authors": "Turf",
  "complete": true,
  "finished": true,
  "have": "1-7",
  "have_nb": 7,
  "serie_nb": 7,
  "language": 2,
  "pix": "comics/neffous1.jpeg"
},
{
  "title": "La Quete de l'Oiseau du Temps",
  "genre": 5,
  "authors": "Serge Le Tendre et Régis Loisel",
  "complete": true,
  "finished": true,
  "have": "1-4",
  "have_nb": 4,
  "serie_nb": 4,
  "language": 2,
  "pix": "comics/quete1.jpeg"
},
{
  "title": "Le Lama Blanc",
  "genre": 1,
  "authors": "Alejandro Jodorowsky et Georges Bess",
  "complete": true,
  "finished": true,
  "have": "1-6",
  "have_nb": 6,
  "serie_nb": 6,
  "language": 2,
  "pix": "comics/lama1.jpeg"
},
{
  "title": "Le Surfer d'Argent",
  "genre": 12,
  "authors": "Moebius, Stan Lee",
  "complete": true,
  "finished": true,
  "have": "1",
  "have_nb": 1,
  "serie_nb": 1,
  "language": 2,
  "pix": "comics/surfer.jpeg"
},
{
  "title": "L'Incal",
  "genre": 11,
  "authors": "Moebius et Alexandro Jodorowsky",
  "complete": true,
  "finished": true,
  "have": "1-6",
  "have_nb": 6,
  "serie_nb": 6,
  "language": 2,
  "pix": "comics/incal1.jpeg"
},
{
  "title": "Ou le regard ne porte pas",
  "genre": 1,
  "authors": "Pont et Abolin",
  "complete": true,
  "finished": true,
  "have": "1,2",
  "have_nb": 2,
  "serie_nb": 2,
  "language": 2,
  "pix": "comics/regard1.jpeg"
},
{
  "title": "Péma Ling",
  "genre": 1,
  "authors": "Georges Bess",
  "complete": true,
  "finished": true,
  "have": "1-5",
  "have_nb": 5,
  "serie_nb": 5,
  "language": 2,
  "pix": "comics/pemaling1.jpeg"
},
{
  "title": "Sky Doll",
  "genre": 4,
  "authors": "Alessandro Barbucci et Barbara Canepa",
  "complete": true,
  "finished": true,
  "have": "1-3",
  "have_nb": 3,
  "serie_nb": 3,
  "language": 2,
  "pix": "comics/skydoll1.jpeg"
},
{
  "title": "Ronin",
  "genre": 11,
  "authors": "Franck Miller",
  "complete": true,
  "finished": true,
  "have": "1",
  "have_nb": 1,
  "serie_nb": 1,
  "language": 1,
  "pix": "comics/ronin.jpeg"
},
{
  "title": "Rising Stars",
  "genre": 12,
  "authors": "Joe Michael Straczynski, Christian Zanier, Keu Cha et Ken Lashley",
  "complete": true,
  "finished": true,
  "have": "1",
  "have_nb": 1,
  "serie_nb": 1,
  "language": 1,
  "pix": "comics/risingstars.jpeg"
},
{
  "title": "Le Fleau des Dieux",
  "genre": 11,
  "authors": "Valérie Mangin et Aleksa Gajic",
  "complete": true,
  "finished": true,
  "have": "1-6",
  "have_nb": 6,
  "serie_nb": 6,
  "language": 2,
  "pix": "comics/fleaudieux1.jpeg"
},
{
  "title": "The Shaolin Cowboy",
  "genre": 4,
  "authors": "Geof Darrow and Lana and Andy Wachowski",
  "complete": true,
  "finished": true,
  "have": "1",
  "have_nb": 1,
  "serie_nb": 1,
  "language": 1,
  "pix": "comics/shaolin-cowboy.jpeg"
},
{
  "title": "Tales of an Imperfect Future",
  "genre": 11,
  "authors": "Alfonso Font",
  "complete": true,
  "finished": true,
  "have": "1",
  "have_nb": 1,
  "serie_nb": 1,
  "language": 1,
  "pix": "comics/imperfect-future.jpeg"
},
{
  "title": "Ghost in the Shell",
  "genre": 11,
  "authors": "Masamune Shirow",
  "complete": false,
  "finished": true,
  "have": "1",
  "have_nb": 1,
  "serie_nb": 2,
  "language": 1,
  "pix": "comics/ghost-in-the-shell.jpeg"
}];

if(typeof module === "object" && typeof module.exports === "object"){
    module.exports = uiModels.comics_data;
}
